---
# handlers file for cuttlefish-app
- name: nginx restart
  service: name=nginx state=restarted

- name: nginx reload
  service: name=nginx state=reloaded

- name: systemd daemon-reload
  systemd:
    daemon_reload: yes
