---
galaxy_info:
  author: openaustralia
  description: Cuttlefish transactional email server
  license: MIT
  min_ansible_version: 2.15
  platforms:
    - name: Ubuntu
      versions:
        - noble   # 24.04
        - jammy   # 22.04

dependencies:
  - role: cuttlefish-postfix
  - role: rvm.ruby
    # The last ruby listed will be set as the default
    rvm1_rubies:
      - "ruby-{{ ruby_version }}"
    rvm1_rvm_check_for_updates: false
    rvm1_install_path: '/usr/local/lib/rvm'
    rvm1_user: 'root'
    rvm1_bundler_install: false
  - role: DavidWittman.redis
    redis_bind: "127.0.0.1"
  - role: cuttlefish-backup
    backup_aws_access_key: "{{ encrypted_backup_aws_access_key | default('') }}"
    backup_secret_access_key: "{{ encrypted_backup_secret_access_key | default('') }}"
    backup_passphrase: "{{ encrypted_backup_passphrase | default('') }}"
    backup_dest: "s3+http://{{ s3_bucket | default('cuttlefish-backups') }}/cuttlefish/"
    backup_inclist:
      - "/var/lib/database-backup"
      - "/srv/www/shared/emails"
